backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

logo_url: "/images/logo-piaget.png"
site_url: "hinstituto-piaget-prueba.vercel.app" # cambia a tu dominio real

locale: 'es' # idioma español en todo el admin

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/home.md"
        label: "Inicio"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descripción", name: "description", widget: "text" }
          - { label: "Contenido", name: "body", widget: "markdown" }
          - { label: "URL de Facebook", name: "facebook_url", widget: "string" }
          - { label: "URL de Instagram", name: "instagram_url", widget: "string" }
          - { label: "Embed Post de Instagram", name: "instagram_embed_url", widget: "string" }
